# MMLB NEEDS MIKES HELP!!!
# AND IS GRATEFUL FOR IT!!!!!!
FROM alpine:latest

ARG GITCOMMIT
ENV GITCOMMIT=${GITCOMMIT:-unknown}
ARG GITBRANCH
ENV GITBRANCH=${GITBRANCH:-unknown}
RUN echo GITCOMMIT=$GITCOMMIT && \
    echo GITBRANCH=$GITBRANCH

CMD env | grep -e GIT -e REV
